// C++ translation of core/src/avm2/object/dispatch_object.rs
// Dispatch list object representation

#ifndef RUFFLE_CORE_AVM2_OBJECT_DISPATCH_OBJECT_H
#define RUFFLE_CORE_AVM2_OBJECT_DISPATCH_OBJECT_H

#include <memory>
#include <mutex>
#include <functional>

// Forward declarations
namespace ruffle {
namespace core {
namespace avm2 {
    template<typename GC> class Activation;
    template<typename GC> class Object;
    template<typename GC> class ScriptObjectData;
    template<typename GC> class TObject;
    namespace events {
        template<typename GC> class DispatchList;
    }
}
}

namespace gc_arena {
    template<typename T> class Gc;
    template<typename T> class GcWeak;
    class Mutation;
}
}

namespace ruffle {
namespace core {
namespace avm2 {
namespace object {

/// Internal representation of dispatch lists as generated by EventDispatcher.
///
/// This object is not intended to be constructed, subclassed, or otherwise
/// interacted with by user code. It exists solely to hold event handlers
/// attached to other objects.
template<typename GC>
class DispatchObject;

/// Weak reference to DispatchObject
template<typename GC>
class DispatchObjectWeak;

/// Data structure for DispatchObject
template<typename GC>
class DispatchObjectData {
private:
    /// Base script object
    std::shared_ptr<ScriptObjectData<GC>> base_;

    /// The dispatch list this object holds.
    /// Using mutex for thread-safe access (RefLock equivalent)
    mutable std::mutex dispatch_mutex_;
    events::DispatchList<GC> dispatch_;

public:
    DispatchObjectData() = default;

    explicit DispatchObjectData(std::shared_ptr<ScriptObjectData<GC>> base)
        : base_(std::move(base)) {}

    ScriptObjectData<GC>* base() { return base_.get(); }
    const ScriptObjectData<GC>* base() const { return base_.get(); }

    events::DispatchList<GC>& dispatch() { return dispatch_; }
    const events::DispatchList<GC>& dispatch() const { return dispatch_; }

    std::unique_lock<std::mutex> lock_dispatch() const {
        return std::unique_lock<std::mutex>(dispatch_mutex_);
    }
};

/// Strong reference to DispatchObject
template<typename GC>
class DispatchObject {
private:
    std::shared_ptr<DispatchObjectData<GC>> data_;

public:
    DispatchObject() = default;
    explicit DispatchObject(std::shared_ptr<DispatchObjectData<GC>> data)
        : data_(std::move(data)) {}

    DispatchObjectData<GC>* data() { return data_.get(); }
    const DispatchObjectData<GC>* data() const { return data_.get(); }

    explicit operator bool() const { return data_ != nullptr; }

    /// Construct an empty dispatch list.
    static Object<GC> empty_list(Activation<GC>* activation);

    /// Get mutable access to the dispatch list
    events::DispatchList<GC>& dispatch_mut(gc_arena::Mutation* mc);
};

/// Weak reference to DispatchObject
template<typename GC>
class DispatchObjectWeak {
private:
    std::weak_ptr<DispatchObjectData<GC>> data_;

public:
    DispatchObjectWeak() = default;
    explicit DispatchObjectWeak(std::weak_ptr<DispatchObjectData<GC>> data)
        : data_(std::move(data)) {}

    DispatchObject<GC> upgrade() const {
        auto locked = data_.lock();
        if (locked) {
            return DispatchObject<GC>(locked);
        }
        return DispatchObject<GC>();
    }

    bool expired() const { return data_.expired(); }
};

} // namespace object
} // namespace avm2
} // namespace core
} // namespace ruffle

#endif // RUFFLE_CORE_AVM2_OBJECT_DISPATCH_OBJECT_H
