// C++ translation of core/common/src/avm_string/common.rs
// Common strings for AVM string interning

#ifndef RUFFLE_CORE_COMMON_AVM_STRING_COMMON_H
#define RUFFLE_CORE_COMMON_AVM_STRING_COMMON_H

#include <cstdint>
#include <array>
#include <memory>

// Forward declarations
namespace ruffle {
namespace core {
namespace avm_string {

template<typename GC>
class AvmAtom;

/// Common strings for AVM string interning
/// Contains frequently used strings to avoid repeated allocations
template<typename GC>
class CommonStrings {
public:
    // ASCII characters (0x00-0x7F)
    std::array<AvmAtom<GC>, 0x80> ascii_chars;

    // Alphanumeric strings, in alphabetical order
    AvmAtom<GC> str_;                    // ""
    AvmAtom<GC> str___constructor__;     // "__constructor__"
    AvmAtom<GC> str___proto__;           // "__proto__"
    AvmAtom<GC> str___resolve;           // "__resolve"
    AvmAtom<GC> str__bytesLoaded;        // "_bytesLoaded"
    AvmAtom<GC> str__bytesTotal;         // "_bytesTotal"
    AvmAtom<GC> str__css;                // "_css"
    AvmAtom<GC> str__listeners;          // "_listeners"
    AvmAtom<GC> str__styles;             // "_styles"
    AvmAtom<GC> str_aa;                  // "aa"
    AvmAtom<GC> str_ab;                  // "ab"
    AvmAtom<GC> str_access;              // "access"
    AvmAtom<GC> str_accessors;           // "accessors"
    AvmAtom<GC> str_addListener;         // "addListener"
    AvmAtom<GC> str_advanced;            // "advanced"
    AvmAtom<GC> str_album;               // "album"
    AvmAtom<GC> str_alphaMultiplier;     // "alphaMultiplier"
    AvmAtom<GC> str_alphaOffset;         // "alphaOffset"
    AvmAtom<GC> str_always;              // "always"
    AvmAtom<GC> str_arguments;           // "arguments"
    AvmAtom<GC> str_artist;              // "artist"
    AvmAtom<GC> str_ascent;              // "ascent"
    AvmAtom<GC> str_asyncError;          // "asyncError"
    AvmAtom<GC> str_auto;                // "auto"
    AvmAtom<GC> str_ba;                  // "ba"
    AvmAtom<GC> str_baseline;            // "baseline"
    AvmAtom<GC> str_baselineConstrained; // "baselineConstrained"
    AvmAtom<GC> str_baselineExtended;    // "baselineExtended"
    AvmAtom<GC> str_bases;               // "bases"
    AvmAtom<GC> str_bb;                  // "bb"
    AvmAtom<GC> str_bigEndian;           // "bigEndian"
    AvmAtom<GC> str_block;               // "block"
    AvmAtom<GC> str_blueMultiplier;      // "blueMultiplier"
    AvmAtom<GC> str_blueOffset;          // "blueOffset"
    AvmAtom<GC> str_bold;                // "bold"
    AvmAtom<GC> str_boldItalic;          // "boldItalic"
    AvmAtom<GC> str_boolean;             // "boolean"
    AvmAtom<GC> str_Boolean;             // "Boolean"
    AvmAtom<GC> str_broadcastMessage;    // "broadcastMessage"
    AvmAtom<GC> str_builtInItems;        // "builtInItems"
    AvmAtom<GC> str_bytesLoaded;         // "bytesLoaded"
    AvmAtom<GC> str_bytesTotal;          // "bytesTotal"
    AvmAtom<GC> str_callee;              // "callee"
    AvmAtom<GC> str_caller;              // "caller"
    AvmAtom<GC> str_caption;             // "caption"
    AvmAtom<GC> str_center;              // "center"
    AvmAtom<GC> str_clamp;               // "clamp"
    AvmAtom<GC> str_click;               // "click"
    AvmAtom<GC> str_code;                // "code"
    AvmAtom<GC> str_color;               // "color"
    AvmAtom<GC> str_comment;             // "comment"
    AvmAtom<GC> str_complete;            // "complete"
    AvmAtom<GC> str_constructor;         // "constructor"
    AvmAtom<GC> str_customItems;         // "customItems"
    AvmAtom<GC> str_data;                // "data"
    AvmAtom<GC> str_declaredBy;          // "declaredBy"
    AvmAtom<GC> str_decode;              // "decode"
    AvmAtom<GC> str_descent;             // "descent"
    AvmAtom<GC> str_description;         // "description"
    AvmAtom<GC> str_device;              // "device"
    AvmAtom<GC> str_doubleClick;         // "doubleClick"
    AvmAtom<GC> str_duration;            // "duration"
    AvmAtom<GC> str_dynamic;             // "dynamic"
    AvmAtom<GC> str_embedded;            // "embedded"
    AvmAtom<GC> str_embeddedCFF;         // "embeddedCFF"
    AvmAtom<GC> str_enabled;             // "enabled"
    AvmAtom<GC> str_error;               // "error"
    AvmAtom<GC> str_extension;           // "extension"
    AvmAtom<GC> str_false;               // "false"
    AvmAtom<GC> str_flushed;             // "flushed"
    AvmAtom<GC> str_focusEnabled;        // "focusEnabled"
    AvmAtom<GC> str_fontStyle;           // "fontStyle"
    AvmAtom<GC> str_fontWeight;          // "fontWeight"
    AvmAtom<GC> str_forward_back;        // "forward_back"
    AvmAtom<GC> str_full;                // "full"
    AvmAtom<GC> str_fullScreen;          // "fullScreen"
    AvmAtom<GC> str_function;            // "function"
    AvmAtom<GC> str_ga;                  // "ga"
    AvmAtom<GC> str_gb;                  // "gb"
    AvmAtom<GC> str_genre;               // "genre"
    AvmAtom<GC> str_global;              // "global"
    AvmAtom<GC> str_greenMultiplier;     // "greenMultiplier"
    AvmAtom<GC> str_greenOffset;         // "greenOffset"
    AvmAtom<GC> str_height;              // "height"
    AvmAtom<GC> str_httpStatus;          // "httpStatus"
    AvmAtom<GC> str_id3;                 // "id3"
    AvmAtom<GC> str_ignore;              // "ignore"
    AvmAtom<GC> str_ignoreWhite;         // "ignoreWhite"
    AvmAtom<GC> str_index;               // "index"
    AvmAtom<GC> str_Infinity;            // "Infinity"
    AvmAtom<GC> str_inline;              // "inline"
    AvmAtom<GC> str_inner;               // "inner"
    AvmAtom<GC> str_input;               // "input"
    AvmAtom<GC> str_interfaces;          // "interfaces"
    AvmAtom<GC> str_ioError;             // "ioError"
    AvmAtom<GC> str_isDynamic;           // "isDynamic"
    AvmAtom<GC> str_isFinal;             // "isFinal"
    AvmAtom<GC> str_isStatic;            // "isStatic"
    AvmAtom<GC> str_italic;              // "italic"
    AvmAtom<GC> str_justify;             // "justify"
    AvmAtom<GC> str_key;                 // "key"
    AvmAtom<GC> str_Key;                 // "Key"
    AvmAtom<GC> str_keyDown;             // "keyDown"
    AvmAtom<GC> str_keyUp;               // "keyUp"
    AvmAtom<GC> str_left;                // "left"
    AvmAtom<GC> str_length;              // "length"
    AvmAtom<GC> str_level;               // "level"
    AvmAtom<GC> str_littleEndian;        // "littleEndian"
    AvmAtom<GC> str_ll;                  // "ll"
    AvmAtom<GC> str_loaded;              // "loaded"
    AvmAtom<GC> str_localhost;           // "localhost"
    AvmAtom<GC> str_localName;           // "localName"
    AvmAtom<GC> str_loop;                // "loop"
    AvmAtom<GC> str_lr;                  // "lr"
    AvmAtom<GC> str_macType;             // "macType"
    AvmAtom<GC> str_matrixType;          // "matrixType"
    AvmAtom<GC> str_menu;                // "menu"
    AvmAtom<GC> str_menuItemSelect;      // "menuItemSelect"
    AvmAtom<GC> str_menuSelect;          // "menuSelect"
    AvmAtom<GC> str_message;             // "message"
    AvmAtom<GC> str_metadata;            // "metadata"
    AvmAtom<GC> str_methods;             // "methods"
    AvmAtom<GC> str_middleClick;         // "middleClick"
    AvmAtom<GC> str_middleMouseDown;     // "middleMouseDown"
    AvmAtom<GC> str_middleMouseUp;       // "middleMouseUp"
    AvmAtom<GC> str_Mouse;               // "Mouse"
    AvmAtom<GC> str_mouseDown;           // "mouseDown"
    AvmAtom<GC> str_mouseMove;           // "mouseMove"
    AvmAtom<GC> str_mouseOut;            // "mouseOut"
    AvmAtom<GC> str_mouseOver;           // "mouseOver"
    AvmAtom<GC> str_mouseUp;             // "mouseUp"
    AvmAtom<GC> str_mouseWheel;          // "mouseWheel"
    AvmAtom<GC> str_movieclip;           // "movieclip"
    AvmAtom<GC> str_name;                // "name"
    AvmAtom<GC> str_NaN;                 // "NaN"
    AvmAtom<GC> str_netStatus;           // "netStatus"
    AvmAtom<GC> str_never;               // "never"
    AvmAtom<GC> str_none;                // "none"
    AvmAtom<GC> str_normal;              // "normal"
    AvmAtom<GC> str_null;                // "null"
    AvmAtom<GC> str_number;              // "number"
    AvmAtom<GC> str_Number;              // "Number"
    AvmAtom<GC> str_object;              // "object"
    AvmAtom<GC> str_onCancel;            // "onCancel"
    AvmAtom<GC> str_onChanged;           // "onChanged"
    AvmAtom<GC> str_onClose;             // "onClose"
    AvmAtom<GC> str_onComplete;          // "onComplete"
    AvmAtom<GC> str_onConnect;           // "onConnect"
    AvmAtom<GC> str_onData;              // "onData"
    AvmAtom<GC> str_onDragOut;           // "onDragOut"
    AvmAtom<GC> str_onDragOver;          // "onDragOver"
    AvmAtom<GC> str_onEnterFrame;        // "onEnterFrame"
    AvmAtom<GC> str_onFullScreen;        // "onFullScreen"
    AvmAtom<GC> str_onHTTPError;         // "onHTTPError"
    AvmAtom<GC> str_onHTTPStatus;        // "onHTTPStatus"
    AvmAtom<GC> str_onID3;               // "onID3"
    AvmAtom<GC> str_onIOError;           // "onIOError"
    AvmAtom<GC> str_onKeyDown;           // "onKeyDown"
    AvmAtom<GC> str_onKeyUp;             // "onKeyUp"
    AvmAtom<GC> str_onLoad;              // "onLoad"
    AvmAtom<GC> str_onLoadComplete;      // "onLoadComplete"
    AvmAtom<GC> str_onLoadError;         // "onLoadError"
    AvmAtom<GC> str_onLoadInit;          // "onLoadInit"
    AvmAtom<GC> str_onLoadProgress;      // "onLoadProgress"
    AvmAtom<GC> str_onLoadStart;         // "onLoadStart"
    AvmAtom<GC> str_onMouseDown;         // "onMouseDown"
    AvmAtom<GC> str_onMouseMove;         // "onMouseMove"
    AvmAtom<GC> str_onMouseUp;           // "onMouseUp"
    AvmAtom<GC> str_onMouseWheel;        // "onMouseWheel"
    AvmAtom<GC> str_onOpen;              // "onOpen"
    AvmAtom<GC> str_onPress;             // "onPress"
    AvmAtom<GC> str_onProgress;          // "onProgress"
    AvmAtom<GC> str_onRelease;           // "onRelease"
    AvmAtom<GC> str_onReleaseOutside;    // "onReleaseOutside"
    AvmAtom<GC> str_onResize;            // "onResize"
    AvmAtom<GC> str_onResult;            // "onResult"
    AvmAtom<GC> str_onRollOut;           // "onRollOut"
    AvmAtom<GC> str_onRollOver;          // "onRollOver"
    AvmAtom<GC> str_onScroller;          // "onScroller"
    AvmAtom<GC> str_onSelect;            // "onSelect"
    AvmAtom<GC> str_onSetFocus;          // "onSetFocus"
    AvmAtom<GC> str_onStatus;            // "onStatus"
    AvmAtom<GC> str_onUnload;            // "onUnload"
    AvmAtom<GC> str_onXML;               // "onXML"
    AvmAtom<GC> str_optional;            // "optional"
    AvmAtom<GC> str_outer;               // "outer"
    AvmAtom<GC> str_parameters;          // "parameters"
    AvmAtom<GC> str_parse;               // "parse"
    AvmAtom<GC> str_parseXML;            // "parseXML"
    AvmAtom<GC> str_pixel;               // "pixel"
    AvmAtom<GC> str_play;                // "play"
    AvmAtom<GC> str_position;            // "position"
    AvmAtom<GC> str_prefix;              // "prefix"
    AvmAtom<GC> str_print;               // "print"
    AvmAtom<GC> str_prototype;           // "prototype"
    AvmAtom<GC> str_push;                // "push"
    AvmAtom<GC> str_quality;             // "quality"
    AvmAtom<GC> str_ra;                  // "ra"
    AvmAtom<GC> str_rb;                  // "rb"
    AvmAtom<GC> str_readonly;            // "readonly"
    AvmAtom<GC> str_readwrite;           // "readwrite"
    AvmAtom<GC> str_redMultiplier;       // "redMultiplier"
    AvmAtom<GC> str_redOffset;           // "redOffset"
    AvmAtom<GC> str_regular;             // "regular"
    AvmAtom<GC> str_releaseOutside;      // "releaseOutside"
    AvmAtom<GC> str_removeListener;      // "removeListener"
    AvmAtom<GC> str_returnType;          // "returnType"
    AvmAtom<GC> str_rewind;              // "rewind"
    AvmAtom<GC> str_right;               // "right"
    AvmAtom<GC> str_rightClick;          // "rightClick"
    AvmAtom<GC> str_rightMouseDown;      // "rightMouseDown"
    AvmAtom<GC> str_rightMouseUp;        // "rightMouseUp"
    AvmAtom<GC> str_rl;                  // "rl"
    AvmAtom<GC> str_rollOut;             // "rollOut"
    AvmAtom<GC> str_rollOver;            // "rollOver"
    AvmAtom<GC> str_rr;                  // "rr"
    AvmAtom<GC> str_save;                // "save"
    AvmAtom<GC> str_Selection;           // "Selection"
    AvmAtom<GC> str_separatorBefore;     // "separatorBefore"
    AvmAtom<GC> str_songname;            // "songname"
    AvmAtom<GC> str_splice;              // "splice"
    AvmAtom<GC> str_Stage;               // "Stage"
    AvmAtom<GC> str_standard;            // "standard"
    AvmAtom<GC> str_standardConstrained; // "standardConstrained"
    AvmAtom<GC> str_standardExtended;    // "standardExtended"
    AvmAtom<GC> str_status;              // "status"
    AvmAtom<GC> str_string;              // "string"
    AvmAtom<GC> str_String;              // "String"
    AvmAtom<GC> str_subpixel;            // "subpixel"
    AvmAtom<GC> str_subtract;            // "subtract"
    AvmAtom<GC> str_success;             // "success"
    AvmAtom<GC> str_super;               // "super"
    AvmAtom<GC> str_tabChildren;         // "tabChildren"
    AvmAtom<GC> str_tabEnabled;          // "tabEnabled"
    AvmAtom<GC> str_target;              // "target"
    AvmAtom<GC> str_textFieldHeight;     // "textFieldHeight"
    AvmAtom<GC> str_textFieldWidth;      // "textFieldWidth"
    AvmAtom<GC> str_TextSnapshot;        // "TextSnapshot"
    AvmAtom<GC> str_toJSON;              // "toJSON"
    AvmAtom<GC> str_toString;            // "toString"
    AvmAtom<GC> str_toXMLString;         // "toXMLString"
    AvmAtom<GC> str_track;               // "track"
    AvmAtom<GC> str_traits;              // "traits"
    AvmAtom<GC> str_transform;           // "transform"
    AvmAtom<GC> str_true;                // "true"
    AvmAtom<GC> str_tx;                  // "tx"
    AvmAtom<GC> str_ty;                  // "ty"
    AvmAtom<GC> str_type;                // "type"
    AvmAtom<GC> str_undefined;           // "undefined"
    AvmAtom<GC> str_uri;                 // "uri"
    AvmAtom<GC> str_useHandCursor;       // "useHandCursor"
    AvmAtom<GC> str_value;               // "value"
    AvmAtom<GC> str_valueOf;             // "valueOf"
    AvmAtom<GC> str_variables;           // "variables"
    AvmAtom<GC> str_visible;             // "visible"
    AvmAtom<GC> str_void;                // "void"
    AvmAtom<GC> str_width;               // "width"
    AvmAtom<GC> str_wrap;                // "wrap"
    AvmAtom<GC> str_writeonly;           // "writeonly"
    AvmAtom<GC> str_xMax;                // "xMax"
    AvmAtom<GC> str_xMin;                // "xMin"
    AvmAtom<GC> str_xml;                 // "xml"
    AvmAtom<GC> str_year;                // "year"
    AvmAtom<GC> str_yMax;                // "yMax"
    AvmAtom<GC> str_yMin;                // "yMin"
    AvmAtom<GC> str_zoom;                // "zoom"

    /// Create CommonStrings with an interning function
    /// @param intern_from_static Function to intern static byte arrays
    template<typename F>
    static CommonStrings create(F intern_from_static);
};

} // namespace avm_string
} // namespace core
} // namespace ruffle

#endif // RUFFLE_CORE_COMMON_AVM_STRING_COMMON_H
